version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
     MONGO_INITDB_ROOT_USERNAME: enrique
     MONGO_INITDB_ROOT_PASSWORD: enrique
     MONGO_INITDB_USERNAME: enrique
     MONGO_INITDB_PASSWORD: enrique
     MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  reddit_middleware:
    image: esegundorolon/reddit-middleware:latest
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
     WAIT_HOSTS: mongodb:27017
     MONGODB_HOST: mongodb
volumes:
  mongodb_data_container: